#docker-compose --profile setup up --build
#docker-compose --profile main up --build

# Backend only
#docker-compose up -d backend

# Frontend only
#docker-compose up -d frontend

services:
  setup:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./StreamKeeper-Node-Backend:/app/StreamKeeper-Node-Backend
      - ./StreamKeeper-React:/app/StreamKeeper-React
    command: node setup.js
    profiles: ["setup"]

  backend:
    build:
      context: ./StreamKeeper-Node-Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
    environment:
      - NODE_ENV=development
    profiles: ["main", "backend"]  # Added individual profile
    env_file:
      - ./StreamKeeper-Node-Backend/.env

  frontend:
    build:
      context: ./StreamKeeper-React
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    profiles: ["main", "frontend"]  # Added individual profile
    depends_on:
      - backend